import { Routes } from '@angular/router';

import { FpoDashboardComponent } from '../../pages/fpo/dashboard/dashboard.component';
import { UserProfileComponent } from '../../pages/user-profile/user-profile.component';

import { BoardMembersComponent } from '../../pages/fpo/board-members/board-members.component';
import { LicenseComponent } from '../../pages/fpo/license/license.component';
import { MachinaryBankComponent } from '../../pages/fpo/machinary-bank/machinary-bank.component';
import { StorageUnitComponent } from '../../pages/fpo/storage-unit/storage-unit.component';
import { CropProductionComponent } from '../../pages/fpo/crop-production/crop-production.component';
import { SalesDetailsComponent } from '../../pages/fpo/sales-details/sales-details.component';
import { ProductionReportComponent } from '../../pages/fpo/production-report/production-report.component';
import { PhotographsComponent } from '../../pages/fpo/photographs/photographs.component';
import { FarmerDetailsComponent } from '../../pages/fpo/farmer-details/farmer-details.component';
import { LandDetailsComponent } from '../../pages/fpo/land-details/land-details.component';
import { AddFarmerComponent } from '../../pages/fpo/add-farmer/add-farmer.component';
import { ProductionDetailsComponent } from '../../pages/fpo/production-details/production-details.component';
import { CropShowingDetailsComponent } from '../../pages/fpo/crop-showing-details/crop-showing-details.component';
import { ComplaintsComponent } from '../../pages/fpo/complaints/complaints.component';
import { ServicesComponent } from '../../pages/fpo/services/services.component';
import { DepartmentDashboardComponent } from '../../pages/department/dashboard/departmentDashboard.component';
import { DepartmentReportComponent } from '../../pages/department/department-report/department-report.component';
import { DepartmentProductionReportComponent } from '../../pages/department/department-production-report/department-production-report.component';
import { DepartmentSalesReportComponent } from '../../pages/department/department-sales-report/department-sales-report.component';
import { DepartmentCircularsComponent } from '../../pages/department/department-circulars/department-circulars.component';
import { DepartmentUplaodCircularComponent } from '../../pages/department/department-uplaod-circular/department-uplaod-circular.component';
import { DepartmentComplaintsComponent } from '../../pages/department/department-complaints/department-complaints.component';
import { DepartmentUserManagementComponent } from '../../pages/department/department-user-management/department-user-management.component';
import { DepartmentAllUsersComponent } from '../../pages/department/department-all-users/department-all-users.component';
import { SearchComponent } from '../..//pages/common/search/search.component';
import { NotificationsComponent } from '../../pages/common/notifications/notifications.component';
import { IndentComponent } from '../../pages/common/indent/indent.component';
import { FarmerUserProfileComponent } from '../../pages/user-profile/farmer-user-profile/farmer-user-profile.component';
import { DepartmentGuidelineComponent } from 'src/app/pages/department/department-guideline/department-guideline.component';
import { DepartmentSchemeComponent } from 'src/app/pages/department/department-scheme/department-scheme.component';
import { FarmerComplaintsComponent } from '../../pages/farmer/farmer-complaints/farmer-complaints.component';
import { BuyerTraderComplaintsComponent } from '../../pages/buyer-treder/buyer-trader-complaints/buyer-trader-complaints.component';
import { InputDetailsSeedsComponent } from 'src/app/pages/Input-Supplier/input-details-seeds/input-details-seeds.component';
import { InputDetailsFertilizerComponent } from 'src/app/pages/Input-Supplier/input-details-fertilizer/input-details-fertilizer.component';
import { InputDetailsMachineryComponent } from 'src/app/pages/Input-Supplier/input-details-machinery/input-details-machinery.component';
import { InputDetailsInsecticidesComponent } from 'src/app/pages/Input-Supplier/input-details-insecticides/input-details-insecticides.component';
import { MachineryComponent } from 'src/app/pages/CHC/machinery/machinery.component';
import { UserStatusComponent } from 'src/app/pages/user-status/user-status.component';
import { ComplaintByFarmerComponent } from '../../pages/fpo/complaint-by-farmer/complaint-by-farmer.component';
import { DepartmentNotificationComponent } from '../../pages/department/department-notification/department-notification.component';
import { FpoNotifiactionComponent } from '../../pages/fpo/fpo-notifiaction/fpo-notifiaction.component';
import { NotifiactionByDepartmentComponent } from '../../pages/fpo/notifiaction-by-department/notifiaction-by-department.component';
import { BuyeruserComponent } from 'src/app/pages/buyer-treder/buyeruser/buyeruser.component';
import { UserProfileDashboardComponent } from 'src/app/pages/user-profile-dashboard/user-profile-dashboard.component';
import { FarmerNotifictionByFpoComponent } from '../../pages/farmer/farmer-notifiction-by-fpo/farmer-notifiction-by-fpo.component';
import { FpoDetailsComponent } from '../../pages/fpo-details/fpo-details.component';
import { DepartmentAllComplaintsComponent } from '../../pages/department/department-all-complaints/department-all-complaints.component';
import { FPOAllUserComponent } from '../../pages/fpo/fpoall-user/fpoall-user.component';
import { FarmerDashboardComponent } from '../../pages/farmer/farmer-dashboard/farmer-dashboard.component';
import { WarehouseComponent } from 'src/app/pages/department/warehouse/warehouse.component';
import { MyFpoComponent } from 'src/app/pages/farmer/my-fpo/my-fpo.component';
import { SupplierDashboardComponent } from 'src/app/pages/Input-Supplier/supplier-dashboard/supplier-dashboard.component';
import { ChhfmbDashboardComponent } from '../../pages/CHC/chhfmb-dashboard/chhfmb-dashboard.component';
import { BuyerDashboardComponent } from '../../pages/buyer-treder/buyer-dashboard/buyer-dashboard.component';

export const AdminLayoutRoutes: Routes = [
  { path: 'fpo/dashboard', component: FpoDashboardComponent },
  { path: 'fpo/user-profile', component: UserProfileComponent },
  { path: 'fpo/board-members', component: BoardMembersComponent },
  { path: 'fpo/license', component: LicenseComponent },
  { path: 'fpo/machinary-bank', component: MachinaryBankComponent },
  { path: 'fpo/storage-unit', component: StorageUnitComponent },
  { path: 'fpo/crop-production', component: CropProductionComponent },
  { path: 'fpo/sales-details', component: SalesDetailsComponent },
  { path: 'fpo/production-report', component: ProductionReportComponent },
  { path: 'fpo/photographs', component: PhotographsComponent },
  { path: 'fpo/farmer-details', component: FarmerDetailsComponent },
  { path: 'fpo/land-details', component: LandDetailsComponent },
  { path: 'fpo/add-farmer', component: AddFarmerComponent },
  { path: 'fpo/production-details', component: ProductionDetailsComponent },
  { path: 'fpo/crop-showing-details', component: CropShowingDetailsComponent },
  { path: 'fpo/services', component: ServicesComponent },
  { path: 'fpo/complaints', component: ComplaintsComponent },
  { path: 'department/dashboard', component: DepartmentDashboardComponent },
  { path: 'department/reports', component: DepartmentReportComponent },
  { path: 'department/production-report', component: DepartmentProductionReportComponent },
  { path: 'department/sales-report', component: DepartmentSalesReportComponent },
  { path: 'department/circulars', component: DepartmentCircularsComponent },
  { path: 'department/upload-circulars', component: DepartmentUplaodCircularComponent },
  { path: 'department/complaints', component: DepartmentComplaintsComponent },  
  { path: 'department/user-management', component: DepartmentUserManagementComponent },
  { path: 'department/all-users', component: DepartmentAllUsersComponent },
  { path: 'department/guideline', component: DepartmentGuidelineComponent },
  { path: 'department/schemes', component: DepartmentSchemeComponent },
  { path: 'department/warehouse', component: WarehouseComponent },
  { path: 'search', component: SearchComponent },
  { path: 'notifications', component: NotificationsComponent },
  { path: 'indent_history', component: IndentComponent },
  { path: 'fpo/farmer-user-profile', component: FarmerUserProfileComponent },
  { path: 'farmer/complaints', component: FarmerComplaintsComponent },
  { path: 'byer/complaints', component: FarmerComplaintsComponent },
  { path: 'chc/complaints', component: FarmerComplaintsComponent },
  { path: 'input/complaints', component: FarmerComplaintsComponent },
  { path: 'input-seed', component: InputDetailsSeedsComponent },
  { path: 'input-fertilizer', component: InputDetailsFertilizerComponent },
  { path: 'input-machinery', component: InputDetailsMachineryComponent },
  { path: 'input-insect', component: InputDetailsInsecticidesComponent },
  { path: 'CHC-machinery', component: MachineryComponent },
  { path: 'userDetails', component: UserStatusComponent },   
  { path: 'fpo/complaintsByfarmer', component: ComplaintByFarmerComponent },
  { path: 'indent_history/buyer-user-profile', component: BuyeruserComponent },
  { path: 'user-profile',component:UserProfileDashboardComponent},
  { path: 'department/dept-notification', component: DepartmentNotificationComponent },
  { path: 'fpo/fpo-notification', component: FpoNotifiactionComponent },
  { path: 'fpo/fpo-notificationByDept', component: NotifiactionByDepartmentComponent },
  { path: 'farmer/farmerNotificationByFpo', component: FarmerNotifictionByFpoComponent },
  { path: 'farmer/myFPo', component: MyFpoComponent },
  { path: 'deptInput/complaints', component: DepartmentAllComplaintsComponent },
  { path: 'deptBuyer/complaints', component: DepartmentAllComplaintsComponent },
  { path: 'deptCHC/complaints', component: DepartmentAllComplaintsComponent },
  { path: 'fpoUser/fpoUser', component: FPOAllUserComponent },
  { path: 'farmer/dashboard', component:FarmerDashboardComponent},
  { path: 'input-supplier/dashboard', component:SupplierDashboardComponent},
  { path: 'chcfmb/dashboard', component: ChhfmbDashboardComponent},
  { path: 'buyer/dashboard', component: BuyerDashboardComponent}
];

